### ISSUE TITLE
Bot did not detect captcha.

### ISSUE THREAD

**Issue by abdullah-nidawi** [thejoabo/virtualfisher-bot#31] opened 2022-09-06 03:22 UTC
I started using the bot today and I setup everything correctly including the API key. The bot worked as it should except when it came to the captcha, it didn't detect it and kept spamming /fish until I got banned for 1 day because the captcha was never solved.

**Comment by thejoabo** [comment] 2022-09-06 13:10
Hello @abdullah-nidawi , I'm sorry that this happened. **Please check this other issue:** #27 

I really can't reproduce this behavior on my environment, I did lots of testing and it was detected every single time. I can't thing about solutions for something that I have no clue whatsoever how it happens. 

I'll be performing some more testing with different accounts thorough this week to see if I can trigger this error.

**Comment by abdullah-nidawi** [comment] 2022-09-06 14:09
Thank you for the reply.
I used the bot on a private channel where I was the only one fishing. The bot's terminal was on fullscreen while discord was out of focus/minimized (maybe that caused the issue?). The bot did about 200 or more successful passes and detected/solved 0 captchas. I used the latest release of the bot. I hope this info helps somehow.

**Comment by thejoabo** [comment] 2022-09-06 14:38
I would need detailed logs and, of course, that this issue happen to me (because I can debug it real-time). I might have an hypothesis about how messages could be ignored but it need more testing. Keep an eye on the next updates. I suggest, if you plan to use this autobot again, to monitor both discord and terminal in order to spot unusual captcha detection behavior and, if so, enable DEBUG on your config files, so you could report it here.

Again, sorry that this happened.

(I'll be closing this issue for now but feel free to re-open it if something else happen)

**Closed by thejoabo** 2022-09-06 14:38 UTC
