### ISSUE TITLE
Captcha error handling

### ISSUE THREAD

**Issue by yudhistiraindyka** [thejoabo/virtualfisher-bot#14] opened 2022-07-23 17:13 UTC
Hello @thejoabo, after using the new version for about 2 days I realized that there might be an issue with the captcha error handling. If I understand correctly, the program should do verify regen after the captcha fails and if it's still incorrect the program would expect us to do manual captcha right? The thing is the fisher bot wouldn't give any response if the captcha is incorrect, therefore it halts the program.

**Comment by thejoabo** [comment] 2022-07-23 17:20
Hello @yudhistiraindyka ,

I'm aware of this problem and already have a fix to it planned (the solution is just implement a timeout exception when x seconds is reached, then the regen command would be triggered). Thanks for reporting, I'm a little busy today so I'll probably fix it tomorrow.

**Comment by RanggaGibran** [comment] 2022-07-24 10:59
![image](https://user-images.githubusercontent.com/101553767/180644000-29c9882f-5bdf-47e5-bf59-ec16ffb3c6c1.png)

sometimes just like this, and got banned for 1 day

![image](https://user-images.githubusercontent.com/101553767/180644013-afd4fb83-b321-4655-b62b-eafe1e6fbab6.png)

**Comment by thejoabo** [comment] 2022-07-24 11:53
@RanggaGibran, **which version of the bot you are running ?** Since [version 1.1.0](https://github.com/thejoabo/virtualfisher-bot/commit/6d613f330897407e7e8af87aa6244bb906538f5e) I changed the captcha handling method and made impossible for the bot to send continuous "_%fish_" messages when a captcha is detected (and also added a redundant verification to check the entire raw event for a match to "_%verify_").

Also, these message patterns doesn't make any sense (for version > 1.0.0):
- when the autobuff routine is triggered the "_fish_paused_" variable is set to True, therefore the main loop halts, and the query sequence is [_'%s all', '%inv', '%stats', '%f'_], so there is no way that a '_%f_' or '_%fish_' message could be sent between the sequence until it ends (which the "_fish_paused_" is set to False again and the main loop would resume);
- the only place in the entire code where a query containing "_%verify regen_" is sent, is hard capped to a maximum of 3 attempts, and for that to be triggered you should get this log on your console `print(f'{captcha.answerList=} | Empty, should regen ! If you are seem this, please open an issue.')`. So there is no way the bot could've sent the regen command this many times and yet fail to detect the captcha every single time;

**Did you made any modification to the source code ? This is a abnormally unusual strange behavior, I can't even imagine a way to reproduce all this "fail-safe" errors in order to perform a troubleshoot.**

Note: as stated on the readme "Keep in mind that this captcha version is not fully finished yet" and therefore shouldn't be left unsupervised for long periods of time. Anyways, everything captcha-related generates some sort of visual alert to the user, I might add a sound alerts in the future (if the interest is enough).

**Comment by Prixm** [comment] 2022-07-25 09:52
I had the same issue last night, the program didn't halt whenever verify regen is required. 

Version 1.1.1

![update](https://user-images.githubusercontent.com/14121768/180749923-3ed6eee0-fd37-4341-8c11-b4dc519c1e62.png)
![paint](https://user-images.githubusercontent.com/14121768/180749122-9a70d866-f1d3-443e-a58a-b0a86ba07ca6.png)
![paint2](https://user-images.githubusercontent.com/14121768/180749146-6d7d432a-bcd7-4b28-aa1f-afed3908b4ae.png)

**Comment by Prixm** [comment] 2022-07-25 10:12
Hello, I had the same issue last night. The problem occurs when the program don't recognize the captcha question and fail to run the %verify regen command since it needs to have captcha.detected condition. 

if captcha.detected and atp <= 3:
            try:
                if captcha.answerList != []:
                    answer = captcha.answerList.pop(0)
                    session.sendQuery(f'%verify {answer}')
                else:
                    atp += 1
                    session.sendQuery('%verify regen')
                    captcha.reset()
            except Exception as e:
                #Failed to send message
                log(f'Manual captcha is required. -> {e}', 'e')

I'm sorry that I don't know much about programming but I think this is where the problem appears.
Thanks for your time, the bot is amazing!

![paint](https://user-images.githubusercontent.com/14121768/180752877-246a5484-d83d-4501-b7b3-2a7c8254f43c.png)

**Comment by thejoabo** [comment] 2022-07-25 14:29
Hello @Prixm , I think the problem lays on the autobuff routine, but I'm really not sure whats going on... Every message that the Virtual Fisher sends to the server is checked, so shouldn't matter which part of the code sent the query. Also, there is a condition in the autobuff routine that should halt while captcha is detected. 

I'm sorry for the inconvenience , for now the only solution I can propose for you and other is not let the autofishbot run for long periods without supervision. **I'm working on version 1.2.0 to fix some of these issues and maximize compatibility, the captcha logic will be revised.**

**Comment by sk3homework** [comment] 2022-07-27 02:21
i cant get ocr api key

**Comment by thejoabo** [comment] 2022-07-27 03:58
Hello @sk3homework, answered here: https://github.com/thejoabo/virtualfisher-bot/issues/19

**Comment by thejoabo** [comment] 2022-07-31 21:24
Fixed on 1.2.0 ([changelog](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/changelog.md#v120---73122-current)). **I'll close for now, please reopen if you ran into similar problems again.**

**Closed by thejoabo** 2022-07-31 21:24 UTC
Labels: bug
