### ISSUE TITLE
[50035] [Invalid Form Body] Still Cant run the bot

### ISSUE THREAD

**Issue by gabeaventh** [thejoabo/virtualfisher-bot#30] opened 2022-09-05 18:30 UTC
hello, tried the bot once more it still showing errors (using the newest commit)

I got `50035` `Invalid Form Body`
![image](https://user-images.githubusercontent.com/7519522/188500377-28fb24fa-bc7b-4fa7-8b59-b6ef08e0b6fc.png)

and also, you still had some old commands that arent removed yet like `%verify` `stats`

**Comment by thejoabo** [comment] 2022-09-05 19:53
Hello @gabeaventh ,

About the error: 
<html><body>


50035 | Invalid form body (returned for both application/json and multipart/form-data bodies), or invalid Content-Type provided
-- | --


</body></html>

The thing is: sometimes the error detail that comes with the response isn't that accurate, **so I need the full output to figure out what really happened to the request**. Please enable DEBUG in your config file and run the bot again to reproduce the error, then copy (or screenshot) your terminal output and send it in my email: dev.joabo@pm.me .

The interactions requests need the "guild_id" and "channel_id" field, as you can see, I didn't request the user to provide the guild id manually, so instead when the websocket respond with the "READY" state (which contains the user and guilds information), it searches every channel id in every guild to find a match. So, for example, if I provide an incorrect channel id, it won't find a match and therefore all requests will be invalid.  

Also, can you check if:
- your config file is properly set up (according to [FAQ](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/faq.md))
- the provided channel id is correct
- the provided channel id is not public (this means, if **only you** are sending/receiving messages in that channel)

About the commands: 

- the "%verify" was replaced by "/verify" (except in the captcha detection, but since it was there as redundancy it didn't become noticeable - or impactful -  in the testing)..
- the "%stats" command was - apparently - completly removed when I inspected the commands object retrieved from the server, but when I checked [their website](https://virtualfisher.com/commands), was still there, so I left an "/stats" query to be sent either way (in case they added it back).

**Comment by gabeaventh** [comment] 2022-09-06 02:42
sure sure, ill send you later, DEBUG MODE already on for me to debug

for config i already checked it the 4th times that my config is correct, including the channel_id

isnt it easier that we put the guild_id to the config, rather than searching it?

**Comment by gabeaventh** [comment] 2022-09-06 04:21
confirmed

i change the `guild_id` manually and disable the auto `guild_id`

it worked flawlessly

**Comment by thejoabo** [comment] 2022-09-06 12:51
Great, I might give the option to manually insert the guild id in the config. 
Two things:
- Did you tried to run it with the patch (1.2.1.1) ? It might have fixed this issue, I was accidentally overwriting the "guild" variable, but for some weird reason it didn't cause any error using my config.
- How often are you getting code 429 ?

**Comment by gabeaventh** [comment] 2022-09-06 12:55
> Great, I might give the option to manually insert the guild id in the config. Two things:
> 
> * Did you tried to run it with the patch (1.2.1.1) ? It might have fixed this issue, I was accidentally overwriting the "guild" variable, but for some weird reason it didn't cause any error using my config.
> * How often are you getting code 429 ?

- i haven't tried it with 1.2.1.1, ill try later after my ban is lifted tomorrow, I accidentally left it while meeting

- quite often, I think after resupply will always get 429

**Comment by thejoabo** [comment] 2022-09-06 13:31
Ok, 429s are a bad sign, they are related with Discord's Rate Limits, but since there is an sleep there, it shouldn't be a problem. Also, about your ban, was it the autobot's fault ? Like, it missed captcha detection or something like that ?

**Comment by gabeaventh** [comment] 2022-09-06 14:30
> Ok, 429s are a bad sign, they are related with Discord's Rate Limits, but since there is an sleep there, it shouldn't be a problem. Also, about your ban, was it the autobot's fault ? Like, it missed captcha detection or something like that ?

Yes it missed the autodetection, to be exact , it used `/fish` command about 13 times before I got banned

don't worry it was working flawlessly, I think it succeed about 8-10 verify when I last check

when I check the logs I found these:
I think there's a time when the bot attempted to reconnect, and the captcha appeared, and the bot solved it
but cannot verify due to the bot still attempting to reconnect and proceed to do `/fish` command after it reconnected

unfortunately, I have to restart my PC to update windows because I postponed it too many times

here's the image of `/fish` command spam
![image](https://user-images.githubusercontent.com/7519522/188661764-0568efdf-8486-4a5f-8610-7b9ae42b84a1.png)

**Comment by thejoabo** [comment] 2022-09-06 15:33
Ok, sorry for that, I'll add a check to set the dispatcher a dormant state when the receiver is not ready. When possible try the latest version to see if the guild problem is solved. Anyways thanks for your patience and help.

**Comment by gabeaventh** [comment] 2022-09-06 16:21
> Ok, sorry for that, I'll add a check to set the dispatcher a dormant state when the receiver is not ready. When possible try the latest version to see if the guild problem is solved. Anyways thanks for your patience and help.

well it's okay, don't be sorry for me that I got banned, my fault anyway, I will try the latest state after the ban lifted

no problem! I actually learned a lot from this project source code and will try to contribute in the near future

actually i wanted to try to fork for `Virtual Farmer Bot` later

**Comment by gabeaventh** [comment] 2022-09-07 08:24
>  Ok, sorry for that, I'll add a check to set the dispatcher a dormant state when the receiver is not ready. When possible try the latest version to see if the guild problem is solved. Anyways thanks for your patience and help.

everything is working as expected, no need to override the `guild_id`, it automatically did it, but just to be safe you can give an option to override the `guild_id`

![image](https://user-images.githubusercontent.com/7519522/188828935-015f919a-36ea-4ce8-8400-404f8949990e.png)

**Comment by thejoabo** [comment] 2022-09-07 14:48
Great then, I'll add a config parameter to set manually the guild id.

**Closed by thejoabo** 2022-09-07 14:48 UTC
Labels: bug
